/*Easy-level problem*/
CREATE TABLE AUTHOR (
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(100),
    COUNTRY VARCHAR(50)
);

CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY,
    BOOK_NAME VARCHAR(100),
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME, COUNTRY) VALUES
(1, 'Author X', 'USA'),
(2, 'Author Y', 'India'),
(3, 'Author Z', 'Canada');

INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, AUTHOR_ID) VALUES
(101, 'Book A', 1),
(102, 'Book B', 2),
(103, 'Book C', 3);
SELECT 
    B.BOOK_NAME,
    A.AUTHOR_NAME,
    A.COUNTRY
FROM 
    BOOKS B
INNER JOIN 
    AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID;
